Starting turn bq submodule.
praekeltfoundation/rdw-ingestion-tools pull request #18
Opened 2024-09-23 12:48 UTC by Schalk1e

Adding support for the various endpoints of the Turn BQ API.

2024-10-01 10:55 UTC, TuscanyBothaReach requested changes
Hey @Schalk1e , thank you for getting me to review this! It helped me to start thinking about the required changes for the ingestion pipeline and to understand how the new API works. 
In addition to the one potential code update, the README also needs a set up instruction for these new endpoints.

2024-10-01 10:55 UTC, TuscanyBothaReach commented on rdw_ingestion_tools/api/turn_bq/requests/cards.py
> +        try:
This try except block gets repeated often - perhaps it could be pulled out into a function to simplify the get methods:
```
def process_generator(generator: Iterator[dict]) -> DataFrame:
    try:
        df = concat([json_normalize(obj, sep="_") for obj in generator])
    except ValueError:
        df = DataFrame()
    return df
```

2024-10-03 07:00 UTC, TuscanyBothaReach approved these changes

2024-10-03 07:00 UTC, TuscanyBothaReach commented on rdw_ingestion_tools/api/turn_bq/extensions/dataframe.py
> +def concatenate(objs: list[dict] | dict | list | Iterator) -> DataFrame:
This works as expected with an empty dictionary, but other dictionaries fail with `NotImplementedError` in the json_normalize step. I see none of the BQ API endpoints return dictionaries, so it's not an issue for those endpoints

2024-10-03 07:48 UTC, TuscanyBothaReach commented on rdw_ingestion_tools/api/turn_bq/extensions/httpx.py
> +        response_data: dict = response_json["items"]
For the BQ API endpoints, I noticed that response_data seems to be a list of dictionaries rather than a single dictionary. Could it be beneficial to use list[dict] as the type hint to better reflect this?

2024-10-03 09:04 UTC, Schalk1e commented on rdw_ingestion_tools/api/turn_bq/extensions/dataframe.py
> +def concatenate(objs: list[dict] | dict | list | Iterator) -> DataFrame:
Perhaps you can elaborate a little on what `other dictionaries` in particular will be problematic. 

We still want any other errors to be raised, so I don't see this as an immediate risk.

2024-10-03 09:05 UTC, merged